# Generated by Django 5.1.5 on 2025-01-26 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftwareInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('software_name', models.CharField(max_length=255, verbose_name='Software Name')),
                ('software_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Software Title')),
                ('software_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Software Address')),
                ('software_email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Software Email')),
                ('software_contact', models.CharField(blank=True, max_length=255, null=True, verbose_name='Software Contact')),
                ('software_logo', models.ImageField(blank=True, null=True, upload_to='software_logos/', verbose_name='Software Logo')),
                ('software_favicon', models.ImageField(blank=True, null=True, upload_to='software_favicons/', verbose_name='Software Favicon')),
                ('software_footer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Software Footer')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Deactivated', 'Deactivated')], default='Active', max_length=15, verbose_name='Status')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Software Info',
                'verbose_name_plural': 'Software Info',
                'db_table': 'SOFTWARE_INFO',
                'ordering': ['-software_name'],
            },
        ),
    ]
