# Generated by Django 5.1.5 on 2025-01-26 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='softwareinfo',
            name='software_footer',
        ),
        migrations.AddField(
            model_name='softwareinfo',
            name='software_dev_by',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='softwareinfo',
            name='software_address',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='softwareinfo',
            name='software_contact',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Contact'),
        ),
        migrations.AlterField(
            model_name='softwareinfo',
            name='software_email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='softwareinfo',
            name='software_favicon',
            field=models.ImageField(blank=True, null=True, upload_to='software_favicons/'),
        ),
        migrations.AlterField(
            model_name='softwareinfo',
            name='software_logo',
            field=models.ImageField(blank=True, null=True, upload_to='software_logos/'),
        ),
        migrations.AlterField(
            model_name='softwareinfo',
            name='software_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='softwareinfo',
            name='software_title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
